version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    # Убираем том для продакшена, чтобы избежать перезаписи файлов контейнера
    # volumes:
    #   - .:/app
    command: npm start
    networks:
      - courserio_network

networks:
  courserio_network:
    external: true
