version: '3.8'

services:
  react-vite-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - courserio_network

networks:
  courserio_network:
    external: true
